bellvat/Chess-App

- app/assets/javascripts/games.coffee
- app/assets/stylesheets/games.scss
- app/controllers/games_controller.rb
- app/helpers/games_helper.rb
- config/routes.rb
- test/controllers/games_controller_test.rb
Hi guys!
Please review the following:
- games controller
- basic methods (index, new, create), and 
- landing(index) page
Thanks!
> Added games controller, basic methods, and created landing(index) page

- app/models/game.rb
- db/migrate/20171021163328_create_games.rb
- db/schema.rb
- test/fixtures/games.yml
- test/models/game_test.rb
@mdunnettstone @tscheitle It would be great it you guys can review the fields migrated in the game model. Thanks! 
I also have a feeling I shouldn't have migrated the changes to the model yet...note for next time.
> Added Game model and added field in game table

- config/database.yml
I believe this should do it.  includes devise user db
> fix database not found error

- app/assets/stylesheets/master.scss
- app/controllers/games_controller.rb
- app/models/game.rb
- app/models/user.rb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_links.html.erb
- config/locales/simple_form.en.yml
- db/migrate/20171023214440_alter_games_add_user_id_column.rb
- db/schema.rb
basic styling...once we come up with a color scheme I will make pretty.  Also wondering if we could do as modal.
> add User authentication, prelim style signIn signUp pages

- app/assets/stylesheets/footer.scss
- app/views/layouts/application.html.erb
- config/database.yml
Here are the bones to the navbar and sticky footer. Devise is hooked up and Sign in/up/out links are functional.
> Header and footer

- app/assets/javascripts/static_pages.coffee
- app/assets/stylesheets/static_pages.scss
- app/controllers/static_pages_controller.rb
- app/helpers/static_pages_helper.rb
- app/views/static_pages/about.html.erb
- app/views/static_pages/home.html.erb
- config/routes.rb
- spec/controllers/static_pages_controller_spec.rb
- spec/helpers/static_pages_helper_spec.rb
Hi all,
I've created 2 static pages: home and about.
**Potential controversy**: I made home the homepage, but if you're logged in, it'll take you straight to the games#index list of games. What does everyone think?
Mike
> Static page routing and controllers

- app/controllers/games_controller.rb
- app/views/games/index.html.erb
- app/views/games/show.html.erb
- config/database.yml
- config/routes.rb
Hi all!
A few things to review:
1. Game#forfeit added a path and a simple form in show.html.erb
2. Added an "if user is signed in" before input of player id's in 'Unmatched simple form' in index.html.erb. The reason for that is because if one player has created a game, and wants to sign out, we are redirected to the index page, and simple form tries to find the id of the second player, who obviously has not joined, and throws an error. If anyone has a suggestion of how to make this cleaner, let me know!
Also, if you are okay with my changes, you can let me know and I can resolve the conflicts, as I was working off an earlier master.
> Feat forfeit

- app/assets/stylesheets/master.scss
- app/views/layouts/application.html.erb
Navbar styled and About page link added
> styled navbar

- .gitignore
- app/assets/stylesheets/font.scss
Created a .gitignore file per instructions on GitHub to handle those pesky Mac addons that keep throwing errors.
Also removed some fonts that I had added and then chose not to use.
> created gitignore file

- app/assets/stylesheets/footer.scss
- app/assets/stylesheets/games.scss
- app/views/games/show.html.erb
Styled chessboard and added boxes for possible additional features such as chat box, move history, and captured pieces.  Easily removed if we decide not to include those.
Bug to be fixed: chessboard scales to mobile as a long rectangle, not square.
> Styled chessboard and added boxes for possible additional features

- app/controllers/games_controller.rb
- app/models/bishop.rb
- app/models/color.rb
- app/models/game.rb
- app/models/game_piece.rb
- app/models/king.rb
- app/models/knight.rb
- app/models/pawn.rb
- app/models/piece.rb
- app/models/queen.rb
- app/models/rook.rb
- app/models/user.rb
- app/views/games/show.html.erb
- db/migrate/20171106110751_drop_game_piece.rb
- db/migrate/20171106111343_add_coordinates_name_color_to_pieces.rb
- db/migrate/20171106112234_create_rooks.rb
- db/migrate/20171106112246_create_bishops.rb
- db/migrate/20171106112259_create_knights.rb
- db/migrate/20171106112307_create_queens.rb
- db/migrate/20171106112313_create_kings.rb
- db/migrate/20171106112323_create_pawns.rb
- db/schema.rb
- db/seeds.rb
- spec/factories.rb
- spec/models/bishop_spec.rb
- spec/models/king_spec.rb
- spec/models/knight_spec.rb
- spec/models/pawn_spec.rb
- spec/models/queen_spec.rb
- spec/models/rook_spec.rb
Models inherit from pieces.
Controllers and initializing of board updated accordingly. Removed other models and updated schema.
Got rid of gamepiece.
Other small tweaks.
> Refactored backend to include single table inheritance

- app/views/games/show.html.erb
Added to J Query to make draggable and droppable smoother
> smoother drag and drop

- app/assets/stylesheets/games.scss
after latest pull chess squares were clear, changed coloring back to white.
> fix white chess square coloring

- README.md
- app/models/game.rb
- app/models/piece.rb
- config/database.yml
- db/schema.rb
Refactored building of array.
Added check if final square has own piece in.
> Is obstructed first pass

- app/models/king.rb
- app/models/knight.rb
- app/models/piece.rb
- spec/factories.rb
- spec/models/king_spec.rb
- spec/models/knight_spec.rb
Set up the basic logic for valid moves by King and Knight.  Set up the following new variables:
In Piece.rb:
x_distance & y_distance - the distance (absolute) between two coordinates
In King.rb & Knight.rb
new_x_coord & new_y_coord - the new coordinates that the piece is moving to.
Also set up tests for each.  All passed.
> King knight valid move

- app/models/bishop.rb
- app/models/piece.rb
- app/models/rook.rb
- spec/models/bishop_spec.rb
- spec/models/rook_spec.rb
Added valid move logic for Rook and Bishop, as well as tests, which all passed.
> Rook bishop valid move

- app/models/bishop.rb
- app/models/piece.rb
- app/models/queen.rb
- app/models/rook.rb
- spec/models/bishop_spec.rb
- spec/models/queen_spec.rb
- spec/models/rook_spec.rb
Basic moves for Queen, excluding obstructions or capture, plus tests
> Queen valid moves

- README.md
- app/models/game.rb
- app/models/piece.rb
- config/database.yml
- db/migrate/20171107164233_drop_all_pieces_tables.rb
- db/schema.rb
Added migration that removes unnecessary piece tables from schema.
> Removed piece tables

- db/schema.rb
- spec/helpers/pieces_helper_spec.rb
- spec/helpers/static_pages_helper_spec.rb
- spec/helpers/users_helper_spec.rb
- spec/models/bishop_spec.rb
- spec/models/game_piece_spec.rb
- spec/models/pawn_spec.rb
- spec/models/piece_spec.rb
Fixed some issues causing testing errors:
- fixed typo in bishop_spec.rb
- deleted file GamePiece_spec.rb as I believe it was leftover from a previous iteration
- deleted all of the language creating pending tests.
All tests now pass as currently written.
> fixed test issues

- app/controllers/pieces_controller.rb
- app/views/games/index.html.erb
- app/views/games/new.html.erb
Hi all,
For this branch, the turn logic is updated to be in the piece controller, and turn_user_id is assigned to the white_player_id in new.html and in index.html.erb.
> Added turn logic to piece controller

- app/models/game.rb
- config/database.yml
Hi all,
White pieces are now at the bottom, which allows white queen to be on white square and black queen on black square.
> Bug piece color switch

- app/controllers/pieces_controller.rb
- app/views/games/show.html.erb
- config/database.yml
HI all,
In order to have the piece move only after a successful Ajax request, 
1. Moved $(this).appendTo.$(ui.draggable) to the success function in Ajax.
2. Added a before action in pieces controller to check for the correct turn
3. Since we are using Ajax, my mentor suggested we don't need to use redirect_to path in piece#update, we just need to know if the call was successful or not, so he suggested render json: [successful status number] instead.
> Feat valid player turn

- app/controllers/pieces_controller.rb
- app/models/piece.rb
Hi All,
Updated the following to check for valid moves:
1. Added a verify_valid_move method in pieces controller, which contains the logic for a valid move (code is brought in from various models and piece.rb). 
The logic includes: a) The piece movement is appropriate b) There are no pieces obstructing the path c) The destination square does not contain the player's own piece
> Feat plug validmove to piececontroller

- app/assets/stylesheets/master.scss
- app/views/games/index.html.erb
This is a very much preliminary styling to make the index less chaotic. 
-Includes CSS for an inverted button to choose black player. 
-For some reason the simple form to show unmatched games will not let me call game.name and insists on linking by game number. If you see why, please let me know or fix it.
> preliminary styling for index page

- app/controllers/games_controller.rb
- app/controllers/pieces_controller.rb
- app/models/piece.rb
- app/views/games/show.html.erb
- config/database.yml
- db/seeds.rb
- spec/controllers/games_controller_spec.rb
- spec/controllers/pieces_controller_spec.rb
- spec/factories.rb
- spec/models/game_spec.rb
- spec/models/piece_spec.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Hi all,
Added tests for methods in the piece model, including for contains_own_piece, is_obstructed and remove_piece.
> Test piece model

- app/controllers/games_controller.rb
- app/controllers/pieces_controller.rb
- app/models/piece.rb
- app/views/games/show.html.erb
- config/database.yml
- db/seeds.rb
- spec/controllers/games_controller_spec.rb
- spec/controllers/pieces_controller_spec.rb
- spec/factories.rb
- spec/rails_helper.rb
- spec/spec_helper.rb
Hi All,
A few things here:
1. Combined verify_player_turn with logic written earlier by Tristen to restrict player from moving opponent's piece
2. Created tests for games controller and piece controller.
3. Moved forfeit logic from view into games controller
4. Fixed a bug in join games -> syntax for find pieces where user_id is nil -> changed from user_id = nil to user_id:nil
5. Fixed is_obstructed to not include the end coordinates
> Tests for Piece and Game Controller

- app/controllers/pieces_controller.rb
- app/models/pawn.rb
- app/models/piece.rb
- spec/controllers/pieces_controller_spec.rb
- spec/models/pawn_spec.rb
Hi all,
This is the code for special pawn diagonal capture that we worked on after the scrum, with some additional code for restricting vertical pawn capture.
Please review and see if any possible improvements!
> Feat pawn capture

- app/assets/stylesheets/games.scss
- app/controllers/pieces_controller.rb
- app/models/piece.rb
- app/views/games/show.html.erb
- config/database.yml
- db/migrate/20171115205409_remove_type_from_pieces.rb
- db/migrate/20171115205949_add_type_to_pieces.rb
- db/migrate/20171115212045_add_captured_to_pieces.rb
- db/schema.rb
Refactored after Monday scrum.
> Piece populates in capture box

- config/database.yml
- db/schema.rb
Merging PR #71 caused error due to database.yml containing Monica's username instead of postgres, and password being empty.  This returns it to what it should be.
> fix error with database.yml login

- app/controllers/pieces_controller.rb
This checks that there are two players in the before action of update.
> verify two players before update

- app/models/pawn.rb
- app/models/piece.rb
Hi All,
This branch allows en passant logic to be called in the controller by adding en passant function to  valid moves function (in pawn.rb).
And allows pawns captured in en passant to be taken off the board into the captured box.
> Added en-passant to valid_move? and updated capture logic 

- app/assets/stylesheets/master.scss
- app/controllers/games_controller.rb
- app/controllers/pieces_controller.rb
- app/models/game.rb
- app/models/piece.rb
- app/views/games/index.html.erb
- db/migrate/20171121234856_add_loser_user_id_to_games.rb
- db/schema.rb
Styled game#index page.  
Added column loser_user_id to db
All works as should - no errors.
> Style game#index

- Gemfile
- Gemfile.lock
- app/assets/javascripts/messages.coffee
- app/assets/stylesheets/master.scss
- app/assets/stylesheets/messages.scss
- app/controllers/games_controller.rb
- app/controllers/messages_controller.rb
- app/helpers/messages_helper.rb
- app/models/game.rb
- app/models/message.rb
- app/views/games/show.html.erb
- config/database.yml
- config/initializers/firebase.rb
- config/routes.rb
- db/migrate/20171121174213_create_messages.rb
- db/schema.rb
- spec/controllers/messages_controller_spec.rb
- spec/factories.rb
- spec/helpers/messages_helper_spec.rb
- spec/models/message_spec.rb
Hi all,
Basic real-time chat functionality added. In summary:
- Messages created that belongs to game and user
- Messages show on game show page, along with new message box
- On submission, creates in actual database, and then sends to firebase
- When firebase detects a new message (almost instant) it appends this to the bottom of the message box
Current drawbacks:
1) Database hosted on my private email address - may need to create ChessSpace@gmail.com or equivalent and change some of the config.
2) Message not currently submitted using ajax, so still refreshes the page on user who submits
3) Because user details not stored in firebase, can't easily call the username - will have to call off user_id somehow
Mike
> Realtime functionality added using Firebase database.

- app/assets/javascripts/application.js
- app/controllers/games_controller.rb
- app/views/games/index.html.erb
- app/views/games/show.html.erb
- config/database.yml
- db/schema.rb
Added destroy action to games controller, and a delete button next to in-progress games in games index
> destroy added to games controller, delete button in games index

- app/assets/stylesheets/games.scss
- app/assets/stylesheets/master.scss
Changed chat box to scroll.
Styled chat message box.
> changed chat box to scroll

- app/controllers/games_controller.rb
- app/controllers/pieces_controller.rb
- app/models/king.rb
- app/models/piece.rb
- app/views/games/index.html.erb
- config/database.yml
- db/migrate/20171115205409_remove_type_from_pieces.rb
- db/migrate/20171124185812_add_state_to_games.rb
- db/schema.rb
- spec/controllers/pieces_controller_spec.rb
- spec/helpers/messages_helper_spec.rb
- spec/models/message_spec.rb
Hi all,
For stalemate:
1. Added 'state' column to games -> will allow us to end a game without updating a winner or loser id for stalemate
**So a stalemate game will be a game with state:"end" but does not have a winner_id or loser_id
2. Modified @completed_games in games_controller to be grouped by games with the state:"end"
**If in your local environment, you have existing completed games, and want them to show up on the index page, you may have to do : rails console, then g = Game.where.not(winner_user_id: nil), then g.update_all(state: "end")
Let me know if you have any comments/suggestions about this way of recording stalemate!
> Feat stalemate

- app/assets/stylesheets/master.scss
- app/controllers/pieces_controller.rb
- app/views/games/index.html.erb
I added some details to show in index, you can see the game opponent and you can delete your own unmatched games. CSS still in progress, but functionality is there. You are welcome to adjust CSS.
> Style index

- app/models/king.rb
Hi all,
I modified any_moves_left function in king.rb in order to fix the false stalemate that renders 201 and interferes with switching player turn.
Let me know if this works for you!
> Fixed bug verify player turn

- app/assets/stylesheets/games.scss
- app/assets/stylesheets/master.scss
- app/views/games/new.html.erb
- app/views/games/show.html.erb
- app/views/static_pages/about.html.erb
Styled all pages except for index to be responsive to mobile devices.  Set 3 breakpoints - up to 600px for mobile phones, up to 1024 for tablets, and above for monitors.  You should notice things grow and shrink as you resize your screen.
> Styled board to be responsive

- app/models/piece.rb
This is the fix from our mob session earlier.
> Bug fix from mob session earlier

- app/assets/stylesheets/games.scss
- app/assets/stylesheets/master.scss
- app/views/games/index.html.erb
Restyled index page to incorporate new buttons.  Had to move some code around but I'm pretty sure everything still works.
> Restyled Index page

- app/assets/stylesheets/master.scss
- app/models/game.rb
- app/views/users/show.html.erb
Added standard styling to user dashboard page.  Also made it responsive.
> Style user dashboard page

- app/controllers/pieces_controller.rb
- app/models/king.rb
- app/models/piece.rb
- db/schema.rb
Hi All!
I branched off of 3castling_logic and modified the following: 
1. So it looks like the villain that kept castling from working was params vs piece_params. Since we have piece_params defined in the pieces_controller for incoming data, we need to use piece_params[x_coord:..].
2. Added an if statement around @rook_for_castling in king.rb because in the case that a @rook_for_castling was not found/nil, server would throw errors.
3. Since we check if the king is in check or if the king is moving itself into check in the pieces_controller, I commented out the code in legal_to_castle that checks those aspects.
4. Added move_number updates for when the king or rook moves when castling.
Let me know your thoughts or concerns for these changes!
> Updated Castling Logic

- app/assets/stylesheets/games.scss
- app/models/piece.rb
- app/views/games/show.html.erb
After piece update:
- sends move to Firebase games/:game_id/pieces
When Firebase updated:
- Pull through latest update for that game, if added in the last 2 seconds
- Reload pages
> Realtime reloading mach 1

- app/assets/stylesheets/games.scss
- app/assets/stylesheets/master.scss
- app/views/games/index.html.erb
- app/views/games/show.html.erb
- db/schema.rb
- Made a few tweaks to responsiveness of game page 
- styled index page to be responsive
> Make index page responsive

- app/controllers/pieces_controller.rb
- app/models/king.rb
- spec/controllers/pieces_controller_spec.rb
- spec/models/king_spec.rb
Hi All,
Fixed bug for king detecting threat from pawn vertical capture and updating castling positions.
> Fixed bug for king detecting check and castling

- app/assets/stylesheets/games.scss
- app/assets/stylesheets/master.scss
- app/models/move.rb
- app/views/games/show.html.erb
Fixed display problems with chat box.
> fixed display issue with chatbox

- app/assets/stylesheets/master.scss
- app/controllers/application_controller.rb
- app/controllers/pieces_controller.rb
- app/views/games/show.html.erb
- app/views/layouts/application.html.erb
Hi All,
This branches allows for alerts to show up for the following: 
1. Invalid player number
2. Invalid player turn
3. Invalid piece move
It does not yet include alerts for "King in check" or "Game end", but we are getting there!
> Bug alert player turn move

- README.md
- db/schema.rb
Changed ReadMe to describe our app.  Will add a screenshot of the board once we get all features working.
> added ReadMe language

- app/views/games/show.html.erb
Hi all,
Fixing a bug for pawn promotion:
- Moved the @pieces for-loop to be before the modal
- Moved Jquery show to be below the Modal
Let me know if this works and/or causes other bugs!
> Moved for-loop before modal

- app/models/game.rb
- app/models/king.rb
- app/views/games/index.html.erb
- app/views/games/show.html.erb
- config/database.yml
- spec/controllers/pieces_controller_spec.rb
Hi all,
For this branch, @denisekelsey created the modal for end game and reroutes the player back to the index page.
Logic for checkmate was slightly modified because the king wasn't detecting that it couldn't capture the threat, since doing that would bring it into another check.
> Endgame Alert

- app/assets/stylesheets/master.scss
- app/controllers/pieces_controller.rb
- app/views/games/show.html.erb
Hi all,
Ended up adding "King is in check" alert message using Jquery.
> Bug flash king in check

- app/controllers/games_controller.rb
- spec/controllers/games_controller_spec.rb
- spec/controllers/pieces_controller_spec.rb
Hi All,
Added flash alert and redirect to index page if player is joining their own game.
Also made minor updates to Rspec.
> Added flash alert and validation for Joining Own Game
